#!/usr/bin/env bash

run () {
  hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id'
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
    stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}' |
      while read -r line; do
        if [[ "1 2 3 4 5 6 7" == *"$line"* ]]; then
          echo $line
        fi
      done
}

run

